# Use Python base image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy requirements.txt into the container
COPY requirement.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirement.txt

# Copy the project files into the container
COPY . .

# Expose the Flask app port
EXPOSE 5000

# Set environment variable to run Flask
ENV FLASK_APP=api.py
ENV FLASK_RUN_HOST=0.0.0.0

# Command to run the Flask app
CMD ["flask", "run"]
